version: '3.9'
services:
  app:
    build: .
    command: sh -c "ng serve --host 0.0.0.0 --port 4200 --disableHostCheck=true --poll=100"
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    tty: true 
    stdin_open: true

